trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: JobA
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]Hello from JobA"
    name: SetVarStep

- job: JobB
  dependsOn: JobA
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: echo "The value of the output variable is $(JobA.SetVarStep.myOutputVar)"
