# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  - name: environments
    value: sit, uat, prod

stages:
  - ${{ each environment in variables.environments}}:
    - stage: ${{ environment }}
      displayName: ${{ environment }}
      ${{ if eq(environment, 'sit')}}:
        dependsOn: []
      ${{ if eq(environment, 'uat')}}:
        dependsOn: sit
      ${{ if eq(environment, 'prod')}}:
        dependsOn: uat
      jobs:
        - job: FirstJob
          steps:
            - script: echo running pipeline for ${{ environment }}
 