# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  - name: environment
    value: sit

stages:
    - stage: First_stage
      displayName: first_stage
      jobs:
        - job: FirstJob
          timeoutInMinutes: 120
          steps:
            - bash: echo "hai ankamma"